### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [17]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [18]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [19]:
# Example 1 - ### your explanation ###
a = torch.tensor([[0,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,1]])
print(torch.bernoulli(a))
b = torch.ones(3, 3)
print(torch.bernoulli(b))
c = torch.zeros(3, 3)
print(torch.bernoulli(c))

tensor([[0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 2 - your function to illustrate

In [22]:
# Example 1 - ### your explanation ###
x = torch.randn(2, 3)
print(x)

y = torch.cat((x, x, x), 0)
print(y)

z = torch.cat((x, x, x), 1)
print(z)

tensor([[-0.4380, -1.4661, -0.5509],
        [-2.5778, -0.2885, -0.6710]])
tensor([[-0.4380, -1.4661, -0.5509],
        [-2.5778, -0.2885, -0.6710],
        [-0.4380, -1.4661, -0.5509],
        [-2.5778, -0.2885, -0.6710],
        [-0.4380, -1.4661, -0.5509],
        [-2.5778, -0.2885, -0.6710]])
tensor([[-0.4380, -1.4661, -0.5509, -0.4380, -1.4661, -0.5509, -0.4380, -1.4661,
         -0.5509],
        [-2.5778, -0.2885, -0.6710, -2.5778, -0.2885, -0.6710, -2.5778, -0.2885,
         -0.6710]])


In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 3 - your function to illustrate

In [23]:
# Example 1 - ### your explanation ###
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [24]:
# Example 2 - ### your explanation ###
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

### Function 4 - your function to illustrate

In [25]:
# Example 1 - ### your explanation ###
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

In [ ]:
# Example 2 - ### your explanation ###
### your code ###